{{- range $i, $svc := .Values.tcp.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  labels:
    {{- include "universal-proxy.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "universal-proxy.selectorLabels" $ | nindent 4 }}
  ports:
  - name: tcp
    port: {{ $svc.servicePort }}
    targetPort: {{ $svc.listenerPort }}
---
{{- end }}